export const configuration = [
  {
    label: 'Job Title',
    key: 'job_title',
    placeholder: '',
    order: 1,
    controlType: 'input',
    is_disabled: false,
    type: 'text',
    isOptionsRequired: false,
    field_uri: null,
    options: {},
    validations: {
      required: true,
      minLength: 1,
      maxLength: 10,
      maxLengthMsg: `Job Title cannot be greater than 10 characters`,
      minLengthMsg: 'Job Title should be greater than 1 charatcter',
      requiredMsg: 'Job title is required',
      validationFunction: 'validateNonMandStringParam',
      validationKey: 'job_title',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      spaceRequired: false,
      readonly: false,
    },
    defaultValue: '',
  },

  {
    pid: 7,
    label: 'Salary',
    key: 'salary',
    placeholder: '',
    order: 2,
    controlType: 'input',
    is_disabled: false,
    type: 'text',
    isOptionsRequired: false,
    field_uri: null,
    options: {},
    validations: {
      required: true,
      requiredMsg: 'Salary is required',
      minLength: 1,
      maxLength: 8,
      maxLengthMsg: 'Salary cannot be greater than 8 characters',
      minLengthMsg: 'Salary cannot be less tan 1 character',
      patternMsg: 'SalaryPatternErrorMsg',
      validationFunction: 'validateStringParam',
      validationKey: 'salary',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      spaceRequired: false,
      readonly: false,
    },
    defaultValue: null,
  },

  {
    pid: 11,
    label: 'Job Provider',
    key: 'provider_pid',
    placeholder: '',
    order: 3,
    controlType: 'select',
    is_disabled: false,
    type: 'select',
    isOptionsRequired: true,
    options: ['P1', 'P2'],
    validations: {
      required: true,
      requiredMsg: 'Please select a job provider',
      validationFunction: 'validateNumber',
      validationKey: 'provider_pid',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      readonly: false,
    },
    defaultValue: null,
  },
  {
    pid: 11,
    label: 'Industry',
    key: 'industry',
    placeholder: '',
    order: 4,
    controlType: 'select',
    is_disabled: false,
    type: 'select',
    isOptionsRequired: true,
    options: ['ABC', 'DEF'],
    validations: {
      required: true,
      requiredMsg: 'Industry is required',
      validationFunction: 'validateNumber',
      validationKey: 'industry',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      readonly: false,
    },
    defaultValue: null,
  },
  {
    pid: 11,
    label: 'Employment Type',
    key: 'emp_type',
    placeholder: '',
    order: 5,
    controlType: 'select',
    is_disabled: false,
    type: 'select',
    isOptionsRequired: true,
    options: ['Full time', 'Temporary'],
    validations: {
      required: true,
      requiredMsg: 'EmploymentType is required',
      validationFunction: 'validateNumber',
      validationKey: 'emp_type',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      nameValue: true,
      readonly: false,
    },
    defaultValue: null,
  },
  {
    pid: 11,
    label: 'Experience Required',
    key: 'exp_req',
    placeholder: '',
    order: 6,
    controlType: 'select',
    is_disabled: false,
    type: 'select',
    isOptionsRequired: true,
    options: [1, 2, 3, 4, 5, 6],
    validations: {
      required: true,
      requiredMsg: 'ExperienceRequiredErrorMsg',
      validationFunction: 'validateNumber',
      validationKey: 'exp_req',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'experience',
      readonly: false,
    },
    defaultValue: null,
  },
  {
    pid: 11,
    label: 'Number of vacancies',
    key: 'vacancy_pid',
    placeholder: '',
    order: 3,
    controlType: 'input',
    is_disabled: false,
    type: 'text',
    isOptionsRequired: true,
    options: [],
    validations: {
      required: true,
      requiredMsg: 'JobProviderRequiredErrorMsg',
      validationFunction: 'validateNumber',
      validationKey: 'provider_pid',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      readonly: false,
    },
    defaultValue: null,
  },
  {
    pid: 11,
    label: 'Job description',
    key: 'description_id',
    placeholder: '',
    order: 3,
    controlType: 'input',
    is_disabled: false,
    type: 'textarea',
    isOptionsRequired: true,
    options: [],
    validations: {
      required: true,
      minLength: 10,
      maxLength: 50,
      maxLengthMsg: `Job Title cannot be greater than 50 characters`,
      minLengthMsg: 'Job Title should be greater than 10 charatcters',
      requiredMsg: 'Job Description is required',
      validationFunction: 'validateNumber',
      validationKey: 'provider_pid',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      readonly: false,
    },
    defaultValue: null,
  },
  {
    label: 'Skills',
    key: 'skills',
    placeholder: '',
    order: 3,
    controlType: 'input',
    is_disabled: false,
    type: 'textarea',
    isOptionsRequired: true,
    options: [],
    multiInputConfig: [
      {
        label: 'skills',
        placeholder: 'Enter skills',
      },
      {
        label: 'Comments',
        placeholder: 'Enter comments',
      },
    ],
    validations: {
      required: true,
      minLength: 10,
      maxLength: 50,
      maxLengthMsg: `Job Title cannot be greater than 50 characters`,
      minLengthMsg: 'Job Title should be greater than 10 charatcters',
      requiredMsg: 'Job Description is required',
      validationFunction: 'validateNumber',
      validationKey: 'provider_pid',
    },
    component: 'mat',
    config: {
      hideLabel: false,
      displayKey: 'industry',
      readonly: false,
    },
    defaultValue: null,
  },
];
